import img from "./image/portfolio.jpg"
import img2 from "./image/portfolio-02.jpg"
import img3 from "./image/portfolio-03.jpg"
const Portfolio_data = [
  {
    id: 6,
    category: "React App",
    totalLike: "690",
    title: "Todo App",
    image: "https://w7.pngwing.com/pngs/670/265/png-transparent-checkmark-done-exam-list-pencil-todo-xomo-basics-icon-thumbnail.png",
    link: "https://lokinder007.github.io/LokeshTodo/" ,
  },
  {
    id: 7,
    category: "React App",
    totalLike: 107,
    title: "Contact App",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQUNx-ZNYGITF4WQYOGQ2TRL1N6HLz4-q6-wg&s",
    link: "https://lokinder007.github.io/contact_app/" ,
  },
  {
    id: 8,
    category: "React App",
    totalLike: "108",
    title: "Student App",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRM2I1EhNdScdVl1qXwPQUkn0lRwctyJp33dQ&s",
    link: "https://lokiwebdev.github.io/student_registration/" ,
  },
  {
    id: 9,
    category: "React App",
    totalLike: "109",
    title: "Trips24",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRyfCL4pv16mx_ycDduYdr7A2oejLhENiNZxCHs1_eXOg&s",
    link: "https://lokiwebdev.github.io/trips24/" ,
  },
  {
    id: 10,
    category: "React App",
    totalLike: "110",
    title: "TodoList",
    image: "https://imageio.forbes.com/specials-images/dam/imageserve/1092571024/960x0.jpg?height=474&width=711&fit=bounds",
    link: "https://lokiwebdev.github.io/todolist/" ,
  },
  {
    id: 1,
    category: "DEVELOPMENT",
    totalLike: "600",
    title: "Loki007",
    image: img,
    link: "https://lokinder007.github.io/loki007/" ,
  },
  {
    id: 2,
    category: "APPLICATION",
    totalLike: "750",
    title: "Portfolio",
    image: img2,
    link: "https://lokinder007.github.io/portfolio2/" ,
  },
  {
    id: 3,
    category: "PHOTOSHOP",
    totalLike: "630",
    title: "Logo design creativity & Application ",
    image: img3,
    link: "https://lokinder007.github.io/loki007/" ,
    // image: "https://rainbowit.net/html/inbio/assets/images/portfolio/portfolio-03.jpg",
  },
  {
    id: 4,
    category: "FIGMA",
    totalLike: "360",
    title: "Mobile app landing design & Services",
    // image: "./image/portfolio-04.jpg",
    image: "https://rainbowit.net/html/inbio/assets/images/portfolio/portfolio-04.jpg",
    link: "https://lokinder007.github.io/loki007/" ,
  },
  {
    id: 5,
    category: "WEB DESIGN",
    totalLike: "280",
    title: "Design for tecnology & services",
    // image: "./image/portfolio-05.jpg",
    image: "https://rainbowit.net/html/inbio/assets/images/portfolio/portfolio-05.jpg",
    link: "https://lokinder007.github.io/loki007/" ,
  },
]
export default Portfolio_data
